name: Sync Issues to Notion

# Trigger on pushes to the (root) branch and on issue events.
on:
  push:
    branches:
      - main
  issues:
    types:
      [
        opened,
        edited,
        closed,
        reopened,
        labeled,
        unlabeled,
        assigned,
        unassigned,
      ]
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  sync-notion:
    runs-on: ubuntu-latest
    # This job will run using the version of the workflow on the (root) branch.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run sync script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: node syncIssuesToNotion.js
