name: Trigger Notion Sync

on:
  issues:
    types:
      [
        opened,
        closed,
        reopened,
        edited,
        assigned,
        unassigned,
        labeled,
        unlabeled,
      ]

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Extract issue data
        id: extract-issue
        uses: actions/github-script@v6
        with:
          script: |
            const { issue } = context.payload;
            const assignees = issue.assignees?.map(a => a.login).join(',') || '';
            const labels = issue.labels?.map(l => l.name).join(',') || '';
            return {
              title: issue.title,
              body: issue.body || '',
              number: issue.number.toString(),
              state: issue.state || 'open',
              labels: labels,
              assignees: assignees
            };
          result-json: issue_data

      - name: Trigger Central Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CENTRAL_REPO_ACCESS_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'ProveItHQ',
              repo: 'notion-workflows',
              workflow_id: 'sync-issues-to-notion.yml',
              ref: 'main',
              inputs: {
                NOTION_DATABASE_ID: '${{ secrets.NOTION_DATABASE_ID }}',
                ISSUE_TITLE: '${{ steps.extract-issue.outputs.title }}',
                ISSUE_BODY: '${{ steps.extract-issue.outputs.body }}',
                ISSUE_NUMBER: '${{ steps.extract-issue.outputs.number }}',
                ISSUE_STATE: '${{ steps.extract-issue.outputs.state }}',
                ISSUE_LABELS: '${{ steps.extract-issue.outputs.labels }}',
                ISSUE_ASSIGNEES: '${{ steps.extract-issue.outputs.assignees }}'
              }
            });
