# File: .github/workflows/notion-sync.yml
# Location: To be created in each repository that needs to sync issues to Notion

name: Sync Issues to Notion

on:
  issues:
    types:
      [
        opened,
        closed,
        reopened,
        edited,
        deleted,
        assigned,
        unassigned,
        labeled,
        unlabeled,
      ]
  workflow_dispatch:
    inputs:
      sync_all:
        description: "Sync all issues (yes/no)"
        required: true
        default: "no"

jobs:
  trigger_central_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Determine issue number
        id: issue
        run: |
          if [[ "${{ github.event_name }}" == "issues" ]]; then
            echo "number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.sync_all }}" == "yes" ]]; then
            echo "number=" >> $GITHUB_OUTPUT
          else
            echo "number=" >> $GITHUB_OUTPUT
          fi

      - name: Trigger Central Workflow
        uses: ProveItHQ/notion-workflows/.github/workflows/handle-repo-dispatch@v1
        with:
          token: ${{ secrets.CENTRAL_REPO_ACCESS_TOKEN }}
          repository: ProveItHQ/notion-workflows
          event-type: sync-issues
          client-payload: '{"repository": "${{ github.repository }}", "issue_number": "${{ steps.issue.outputs.number }}", "notion_database_id": "${{ secrets.NOTION_DATABASE_ID }}"}'
