name: Sync GitHub Issues to Notion
on:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled]
  workflow_dispatch:
  push:
    branches:
      - (root)
permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: read
jobs:
  sync-issues:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/(root)' # Only run on (root) branch
    steps:
      - name: Sync to Notion
        uses: tryfabric/notion-github-action@v1
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-db: ${{ secrets.NOTION_DATABASE_ID }}
